language: java
jdk:
- openjdk11
services:
- postgresql
before_install:
- psql -c 'create database forum;' -U postgres
install: true
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: "-for.viy@gmail.com"
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN="b94bf4d3-8ecf-4f3b-aa55-b4c312fc7015"
deploy:
  provider: heroku
  app: immense-shore-93521
  api_key:
    secure: M2bA9HrZLDT415rE9y8ffC63R8BAqkUOcyfzucIy1OnKEE9ArK937rlQqEQkkfVb4nk4zCu9lK7Di6COJC86JgvAPA7UQA8UgZN4NQM8EcoxDL9JS3IEbIMXxc+6j8hnAhhus9Ws2730Fcze+zvfFRdA8rGC5v1vNBqwCm24dyROHtl83tVBI8yq1MHCSa0FNiuYHAkIZ+O1DvcuGnGcFI8+t6MNHbsSLp0S0KJ3sRd03IYOQWfynyeSpP0hZzVNX5f6ejzMtpw6yOb0gnwVEbGFTgpBUb84ApDmFbFf8CVLVcPEvxs+cGq7RBEn6U1cpwZpn4tuqxxP+LhqsF4HqJvXxXQrQ46DrrwKWLwPCbxqV5mZoeK8Q1Jzv7tXn2ZiJc5/+YgeFtRyYmF/V5UWHqTOmCQf2txKaX3RD0IJ9isGEIm9o4/qLpsH6ZL8fWghxUxly2USc3JZDOLef8ct6xFAmfSkyDoHdgqHeEwDoHCHy5xjuXJb67tU06zv+mce0/e7DT4G18+79y1I6iZgXnvS7GcpLCZjVo5d3Pz97FYr1CYl4aT1ubFG4Yd7AVV6weHA0KQ6XqXmiz3vGYbfnNVZum5tPjFkkdieYZ7lh7fWXkfIcEEzfJfj3CDCBhbWU+zwgMVJtaiQxOw0hs/D0U7GqTVeKAT5OurEbwhWXXA=
